# Generated by Django 5.0.7 on 2024-08-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_userAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='İs_blogAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
