# Generated by Django 5.0.7 on 2024-08-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_is_useradmin_user_i_s_blogadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_userAdmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='İs_blogAdmin',
        ),
    ]
